# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: 'centos7'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    #javaHomeOption: 'Path'
    #jdkDirectory: '/usr/lib/jvm/jre-openjdk'
    mavenVersionOption: 'Path'
    mavenDirectory: '/opt/maven'
    mavenOptions: '-Xmx2024m'
    mavenSetM2Home: true
    